imports/api/champions/range.js, imports/api/champions/server/getRange.js, imports/api/riot-api/static/champions.js, imports/startup/server/admin.js
=> feat(champions): add range field

.meteor/packages, .meteor/versions, babel.config.js, imports/api/trophies/calculateTrophies.ts, imports/api/trophies/trophies.ts, package-lock.json, package.json, tsconfig.json
This allows to use typescript in our Meteor projects.
In #32 I already use typescript for the new services.
=> feat: add typescript support

imports/api/riot-api/server/cache.js, imports/api/riot-api/server/methods.js, imports/api/riot-api/server/riotApi.js, imports/api/trophy-hunters/server/methods/_handleLogin.js, imports/startup/app/server/create-user-hook.js, src/api/endpoints/summoner/index.ts, src/api/endpoints/timeline/index.ts, src/api/server.ts, src/api/shared/riot-api/index.ts, src/api/shared/th-api/index.ts
Endpoint (still v3 of Riot API):
https://www.th.gl/api/summoner?platformId=euw1&summonerId=30118891
=> feat(api): add summoner api

imports/api/riot-api/server/cache.js, imports/api/riot-api/server/methods.js, imports/api/riot-api/server/riotApi.js, src/api/endpoints/champion-mastery/index.ts, src/api/endpoints/trophies/index.ts, src/api/server.ts, src/api/shared/riot-api/index.ts, src/api/shared/th-api/getChampionMastery.ts
=> feat(api): add champion-mastery

imports/api/riot-api/server/methods.js, imports/api/riot-api/server/riotApi.js, src/api/endpoints/summoner/index.ts, src/api/shared/riot-api/index.ts, src/api/shared/th-api/getSummoner.ts
makes it possible to get summoner by accountId and summonerName
=> feat(api): add summoner api variants

imports/api/riot-api/server/cache.js, imports/api/riot-api/server/methods.js, imports/api/riot-api/server/riotApi.js, src/api/endpoints/active-game/index.ts, src/api/endpoints/champion-mastery/index.ts, src/api/endpoints/league-positions/index.ts, src/api/endpoints/match/index.ts, src/api/endpoints/matchlist/index.ts, src/api/endpoints/summoner/index.ts, src/api/endpoints/timeline/index.ts, src/api/endpoints/trophies/index.ts, src/api/server.ts, src/api/shared/riot-api/index.ts, src/api/shared/th-api/getMatchList.ts, src/api/shared/th-api/index.ts
=> feat(api): add matchlist

.vscode/settings.json, imports/api/overwolf/overwolf.js, imports/api/riot-api/server/methods.js, imports/api/trophy-hunters/server/methods/_handleLogin.js, imports/startup/app/server/create-user-hook.js, imports/ui/layouts/AppLayout.js, overwolf/src/shared/lib/launcherListener.js, src/api/endpoints/match/index.ts, src/api/endpoints/matchup/index.ts, src/api/shared/th-api/getMatch.ts
`getMatchup` is the first api which uses v4 of riot api (#40).
I will prepare the login logic to allow login by summonerName. We won't be able to get the summonerId or accountId anymore.
=> feat(api): prepare login logic fo riot v4

CHANGELOG.md, imports/api/riot-api/static/items.js, imports/api/riot-api/static/perks.js, imports/api/riot-api/static/summonerSpells.js, imports/api/riot-api/version.js, src/api/shared/riot-api/champions.ts
See patch notes on https://euw.leagueoflegends.com/en/news/game-updates/patch/patch-91-notes
=> fix(api): update riot api to 9.1.1

imports/api/jobs/server/refreshMatchForGameSession.js, src/api/endpoints/active-game/index.ts, src/api/shared/th-api/getActiveGame.ts
I had the issue that the overlay showed an old match. I guess it is due to the caching.
=> fix(api): stop caching active match

imports/startup/project/project.js
Match details didn't work on www.loltrophyhunter.com
=> fix(ui): add game missing route to project

imports/api/badges/_generateBadgesByParticipantPerformance.js, imports/api/matches/server/methods.js, imports/api/utilities/safeParseInt.js, imports/store/actions/_participantMatches.js, imports/store/actions/_participantsHeatmap.js, imports/store/actions/_participantsPerformance.js, imports/store/actions/_playedTogether.js, imports/ui/pages/match/LegacyMatch.js, src/api/endpoints/matchup/index.ts, src/api/endpoints/summoner/index.ts, src/api/shared/th-api/getSummoner.ts
We got blacklisted because of /summoner api calls. I guess it is because of invalid v3/v4 detection.
=> fix(api): fix version check for summonerId

imports/api/game-sessions/server/methods.js, imports/api/trophy-hunters/server/methods/_spectateCurrentMatch.js, imports/api/trophy-hunters/server/methods/loginTrophyHunter.js, src/api/endpoints/timeline/index.ts
It is fine if getActiveGame is not found and should not abort the methods.
=> fix(api): catch getActiveGame error if game not found

src/creator/.babelrc, src/creator/README.md, src/creator/components/JSONEditor.tsx, src/creator/components/LoadMatch.tsx, src/creator/components/Match.tsx, src/creator/components/types.ts, src/creator/next.config.js, src/creator/package.json, src/creator/pages/index.tsx, src/creator/shared, src/package.json, src/www/.babelrc, src/yarn.lock
fixes #62 
this branch adds a new symlink, so make sure to checkout with admin rights on Windows.
Test:
- `cd src`
- `yarn`
- `yarn creator`
=> feat: add creator website

CHANGELOG.md, README.md, imports/api/alerts/alerts.js, imports/api/alerts/server/methods.js, imports/api/overwolf/overwolf.js, imports/api/riot-api/endpoints.js, imports/startup/app/server/register-api.js, src/overwolf/package.json, src/overwolf/shared/lib/launcherListener.js
fixes #82 
this is interesting. I am not sure for how long LAS was not supported.
for some reason the https://developer.riotgames.com/regional-endpoints.html doesn't contain LA2 as region. 
I added a Slack alert when a client has a unsupported region to notify us.
=> fix(api): add LA2 support

src/creator/components/LoadMatch.tsx, src/creator/pages/index.tsx
I had to investigate why a match check failed and added these input fields to the creator website.
This is very helpful.
=> feat(creator): add platformId and matchId input

CHANGELOG.md, imports/ui/components/TrophiesObtained/TrophiesObtained.js
=> fix(ui): display of tree bonus for multiple trees

src/creator/package.json, src/creator/pages/index.tsx, yarn.lock
Storing the active state in LocalStorage didn't work.
=> fix(creator): fix local storage usage

src/app/imports/api/champions/server/updateChampionGGStats.js, src/app/imports/api/server-stats/server/index.js, src/app/imports/startup/app/server/jobs.js
=> fix(champions): make sure to safe role returned by champion.gg

package.json, src/app/.storybook/config.js, src/app/.storybook/stubs/meteor/accounts-base.js, src/app/.storybook/stubs/meteor/aldeed_schema-index.js, src/app/.storybook/stubs/meteor/check.js, src/app/.storybook/stubs/meteor/http.js, src/app/.storybook/stubs/meteor/lmachens_user-presence.js, src/app/.storybook/stubs/meteor/meteor.js, src/app/.storybook/stubs/meteor/mongo.js, src/app/.storybook/stubs/meteor/react-meteor-data.js, src/app/.storybook/stubs/meteor/tracker.js, src/app/.storybook/stubs/meteorPublishJoin.js, src/app/.storybook/webpack.config.js, src/app/imports/ui/layouts/StorybookLayout.js, src/app/package-lock.json, src/app/package.json
We removed storybook temporary because of new folder structure.
It is now only added for the `app` project.
=> feat: add storybook for app again

src/shelf/next.config.js, src/shelf/pages/_app.tsx, src/shelf/pages/_bootstrap.ts, src/www/next.config.js, src/www/pages/_app.tsx, src/www/pages/_bootstrap.ts
Reverts lmachens/trophy-hunter#123
=> Revert "fix: @material-ui/styles install usage was incorrect"

src/app/imports/api/riot-api/static/items.js, src/app/imports/api/riot-api/static/summonerSpells.js, src/app/imports/api/riot-api/version.js, src/app/public/CHANGELOG.md, src/shared/riot-api/champions.ts
See https://na.leagueoflegends.com/en/news/game-updates/patch/patch-93-notes
=> feat: update riot api to 9.3.1

src/api/endpoints/played-together/index.ts, src/api/server.ts
Missing endpoint
New endpoint played-together.
I changed the existing logic to allow the usage of summerName instead of summerId. This makes it much more flexible.
https://api.th.gl/played-together?platformId=euw1&summonerName=sirlunchalot619&summonerName=ComplexityNP&summonerName=Aromakekse
=> [api] feat: create played-together endpoint

packages/api/endpoints/trophy-hunter/index.ts, packages/www/components/Summoner/Summoner.tsx, packages/www/components/SummonerInfo/SummonerInfo.tsx, packages/www/components/Trophies/Trophies.tsx, packages/www/components/Trophy/Trophy.tsx, packages/www/pages/_document.tsx, tslint.json
New summoner page is in progress. Trophies/badges and trophy hunter stats are missing.
Features added. Still needs good layout.
=> [www] add trophies, badges and trophy hunter stats

packages/app/imports/ui/pages/match/Match.js, packages/app/public/CHANGELOG.md
We have a link to a not existing page in the match details
Remvoed that link as long as we don't have the web version for matches.
=> [app]: fix: remove view on web link

packages/app/imports/api/riot-api/static/items.js, packages/app/imports/api/riot-api/static/perks.js, packages/app/imports/api/riot-api/static/summonerSpells.js, packages/app/public/CHANGELOG.md, packages/shared/riot-api/champions.ts, packages/shared/riot-api/version.ts
Riot API 9.3.1
Riot API 9.4.1
Run App
=> [app]: feat: update riot api to 9.4.1

packages/app/imports/api/riot-api/version.js, packages/app/public/CHANGELOG.md, packages/creator/api/getStaticData.ts, packages/creator/pages/static-data.tsx, packages/shared/riot-api/champions.ts, packages/shared/riot-api/perks.ts, packages/shared/riot-api/version.ts, packages/www/components/Match/Match.tsx
Outdated Riot API 9.4.1
Updated to 9.5.1
=> feat: update riot api to 9.5.1

packages/app/public/CHANGELOG.md, packages/creator/api/getStaticData.ts, packages/creator/pages/static-data.tsx, packages/shared/riot-api/champions.ts, packages/shared/riot-api/items.ts, packages/shared/riot-api/perks.ts, packages/shared/riot-api/version.ts
=> feat: update riot api to 9.6.1

packages/app/public/CHANGELOG.md, packages/shared/trees/definitions/ahri1.ts, packages/shared/trees/definitions/amumu1.ts, packages/shared/trees/definitions/nasus1.ts, packages/shared/trees/definitions/nautilus1.ts, packages/shared/trees/definitions/ziggs1.ts, packages/shared/trees/index.ts
Five new trees for April 2019
Storybook
=> feat: add april trees

packages/app/public/CHANGELOG.md, packages/shared/trees/definitions/neeko1.ts, packages/shared/trees/definitions/twistedFate1.ts, packages/shared/trees/definitions/xinZhao1.ts, packages/shared/trees/definitions/yasuo1.ts, packages/shared/trees/definitions/yorick1.ts, packages/shared/trees/index.ts
=> feat: add mai trees

packages/app/imports/api/riot-api/version.js, packages/app/public/CHANGELOG.md, packages/shared/riot-api/champions.ts, packages/shared/riot-api/items.ts, packages/shared/riot-api/perks.ts, packages/shared/riot-api/summonerSpells.ts, packages/shared/riot-api/version.ts
=> feat: update riot api 9.9.1

packages/app/imports/api/riot-api/version.js, packages/app/public/CHANGELOG.md, packages/shared/riot-api/champions.ts, packages/shared/riot-api/perks.ts, packages/shared/riot-api/version.ts
=> update riot api

packages/app/imports/api/trophies/getActiveQuestTrophies.js, packages/app/public/CHANGELOG.md, packages/shared/trees/definitions/hecarim1.ts, packages/shared/trees/definitions/jarvanIV1.ts, packages/shared/trees/definitions/poppy1.ts, packages/shared/trees/definitions/sylas1.ts, packages/shared/trees/definitions/vladimir1.ts, packages/shared/trees/index.ts
=> add september 2019 trees

packages/app/imports/ui/components/CustomTreeSelector/CustomTreeSelector.js, packages/app/public/CHANGELOG.md, packages/shared/trees/definitions/rekSai1.ts, packages/shared/trees/index.ts
=> add reksai tree and set active trees

packages/app/imports/api/riot-api/version.js, packages/app/public/CHANGELOG.md, packages/shared/riot-api/champions.ts, packages/shared/riot-api/items.ts, packages/shared/riot-api/perks.ts, packages/shared/riot-api/summonerSpells.ts, packages/shared/riot-api/version.ts
=> Update Riot-API 9.24.1
